# Compose fileのバージョン指定
version: "3"

# どんなコンテナを立ち上げるか
services:

# データベース(maria DB)を動かすコンテナ
  kita_lunch_db:
    container_name: kita_lunch_db

    # Docker Hubからmaria DBの最新版の公式イメージをダウンロードしてくる指定
    image: mariadb:latest

    # どのネットワークにつなげるのか指定
    networks:
      - kita_lunch
    # platform: linux/amd64

    # コンテナ内の環境変数を指定
    environment:
      - MYSQL_ROOT_PASSWORD=!root
      - MYSQL_DATABASE=kita_lunch
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Asia/Tokyo

    # 起動時のコマンド
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    # ディレクトリ同期。設定ファイルとMySQLのデータが保存される場所を同期している。
    # コンテナは基本的に起動時に変更されてもコンテナ自体が止まるとデータが消えてしまうため、
    # 保存しておきたいものはホストマシンを参照させる
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      # データベースを登録する
      # - ./mysql/init:/docker-entrypoint-initdb.d
      # 記憶領域のマウントを指定
      - mysql-vol:/var/lib/mysql
   
    # どのポートを開いて繋ぐか。下記はコンテナの3306番ポートを開いて、ホストの3308番につなぐ
    ports:
      - "3308:3306"
    restart: always

  phpmyadmin:
    container_name: phpMyAdmin

    # Docker Hubから最新版の公式イメージをダウンロードしてくる指定
    image: phpmyadmin/phpmyadmin:latest

    # コンテナ内の環境変数を指定
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=kita_lunch_db
      # - PMA_USER=test
      # - PMA_PASSWORD=test
    
    # どのポートを開いて繋ぐか。下記はコンテナの80番ポートを開いて、ホストの4040番につなぐ
    ports:
      - 4040:80
    # セッション情報をボリュームに設定して永続化
    volumes:
      - ./phpmyadmin/sessions:/sessions

    networks:
      - kita_lunch

networks:
  kita_lunch:
  # app_net:
  #   ipv4_address: 172.21.0.1

# ドッカー内の記憶領域の設定
volumes:
  # データベースの記憶領域のマウントを指定
  mysql-vol:
